// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: basic.proto

#include "basic.pb.h"
#include "basic.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace chat {

static const char* Connect_method_names[] = {
  "/chat.Connect/SayHello",
};

std::unique_ptr< Connect::Stub> Connect::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Connect::Stub> stub(new Connect::Stub(channel, options));
  return stub;
}

Connect::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SayHello_(Connect_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Connect::Stub::SayHello(::grpc::ClientContext* context, const ::chat::HelloRequest& request, ::chat::HelloReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chat::HelloRequest, ::chat::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SayHello_, context, request, response);
}

void Connect::Stub::async::SayHello(::grpc::ClientContext* context, const ::chat::HelloRequest* request, ::chat::HelloReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chat::HelloRequest, ::chat::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, std::move(f));
}

void Connect::Stub::async::SayHello(::grpc::ClientContext* context, const ::chat::HelloRequest* request, ::chat::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chat::HelloReply>* Connect::Stub::PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::chat::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chat::HelloReply, ::chat::HelloRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SayHello_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chat::HelloReply>* Connect::Stub::AsyncSayHelloRaw(::grpc::ClientContext* context, const ::chat::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSayHelloRaw(context, request, cq);
  result->StartCall();
  return result;
}

Connect::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Connect_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Connect::Service, ::chat::HelloRequest, ::chat::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Connect::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chat::HelloRequest* req,
             ::chat::HelloReply* resp) {
               return service->SayHello(ctx, req, resp);
             }, this)));
}

Connect::Service::~Service() {
}

::grpc::Status Connect::Service::SayHello(::grpc::ServerContext* context, const ::chat::HelloRequest* request, ::chat::HelloReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace chat

