# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: basic.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='basic.proto',
  package='chat',
  syntax='proto3',
  serialized_options=b'Z\020generated_files/',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x62\x61sic.proto\x12\x04\x63hat\"\x1d\n\rclientRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\x0eserverResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2F\n\x07\x43onnect\x12;\n\x08SayHello\x12\x13.chat.clientRequest\x1a\x14.chat.serverResponse\"\x00(\x01\x30\x01\x42\x12Z\x10generated_files/b\x06proto3'
)




_CLIENTREQUEST = _descriptor.Descriptor(
  name='clientRequest',
  full_name='chat.clientRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='chat.clientRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=50,
)


_SERVERRESPONSE = _descriptor.Descriptor(
  name='serverResponse',
  full_name='chat.serverResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='chat.serverResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['clientRequest'] = _CLIENTREQUEST
DESCRIPTOR.message_types_by_name['serverResponse'] = _SERVERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

clientRequest = _reflection.GeneratedProtocolMessageType('clientRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTREQUEST,
  '__module__' : 'basic_pb2'
  # @@protoc_insertion_point(class_scope:chat.clientRequest)
  })
_sym_db.RegisterMessage(clientRequest)

serverResponse = _reflection.GeneratedProtocolMessageType('serverResponse', (_message.Message,), {
  'DESCRIPTOR' : _SERVERRESPONSE,
  '__module__' : 'basic_pb2'
  # @@protoc_insertion_point(class_scope:chat.serverResponse)
  })
_sym_db.RegisterMessage(serverResponse)


DESCRIPTOR._options = None

_CONNECT = _descriptor.ServiceDescriptor(
  name='Connect',
  full_name='chat.Connect',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=87,
  serialized_end=157,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='chat.Connect.SayHello',
    index=0,
    containing_service=None,
    input_type=_CLIENTREQUEST,
    output_type=_SERVERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONNECT)

DESCRIPTOR.services_by_name['Connect'] = _CONNECT

# @@protoc_insertion_point(module_scope)
