# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import basic_pb2 as basic__pb2


class ConnectStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.stream_stream(
                '/chat.Connect/SayHello',
                request_serializer=basic__pb2.clientRequest.SerializeToString,
                response_deserializer=basic__pb2.serverResponse.FromString,
                )


class ConnectServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayHello(self, request_iterator, context):
        """Sends a greeting
        rpc SayHello (HelloRequest) returns (HelloReply) {}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.stream_stream_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=basic__pb2.clientRequest.FromString,
                    response_serializer=basic__pb2.serverResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.Connect', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Connect(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHello(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/chat.Connect/SayHello',
            basic__pb2.clientRequest.SerializeToString,
            basic__pb2.serverResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
